# Generated by Django 5.1.4 on 2024-12-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('imagen_producto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, unique=True)),
                ('permiso', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'roles_y_permisos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('admin', 'Admin')], default='cliente', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id_diseño', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_diseño', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_diseño', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('personalizado', 'Personalizado')], default='generado', max_length=20)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diseños',
            },
        ),
        migrations.CreateModel(
            name='HistorialIA',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('imagen_generada', models.CharField(max_length=255)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_IA',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en producción', 'En producción'), ('enviado', 'Enviado')], default='pendiente', max_length=20)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('diseño', models.ForeignKey(db_column='id_diseño', on_delete=django.db.models.deletion.CASCADE, to='selta.diseño')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='Personalizacion',
            fields=[
                ('id_personalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_personalizacion', models.CharField(max_length=150)),
                ('valores', models.JSONField()),
                ('fecha_personalizacion', models.DateTimeField(auto_now_add=True)),
                ('diseño', models.ForeignKey(db_column='id_diseño', on_delete=django.db.models.deletion.CASCADE, to='selta.diseño')),
            ],
            options={
                'db_table': 'personalizaciones',
            },
        ),
    ]
