# Generated by Django 5.2 on 2025-06-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialia',
            name='imagen_generada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
